from __future__ import annotations

FIRST_CYCLE_ATR_PERIOD = 14
FIRST_CYCLE_ATR_MULTIPLIER = 2.0
FIRST_CYCLE_RISK_FRACTION = 0.005
FIRST_CYCLE_DAILY_LOSS_LIMIT = 0.02
FIRST_CYCLE_MAX_DRAWDOWN_HALT = 0.08

EXECUTION_POLICY_VERSION = 1
EXECUTION_POLICY_NAME = "trend_v1_atr14x2_risk0.5pct_spot"
